# Generated by Django 4.1.6 on 2023-03-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='address',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='detail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
